keyboard:
  - key: left
    down: !switch_updated
      name: left_flipper_button
      active: true
    up: !switch_updated
      name: left_flipper_button
      active: false

  - key: right
    down: !switch_updated
      name: right_flipper_button
      active: true
    up: !switch_updated
      name: right_flipper_button
      active: false

  - key: right
    left_shift: true
    down: !switch_updated
      name: right_fire_button
      active: true
    up: !switch_updated
      name: right_fire_button
      active: false

  - key: return
    down: !switch_updated
      name: start_button
      active: true
    up: !switch_updated
      name: start_button
      active: false

  # Drain
  - key: delete
    down: !switch_updated
      name: trough_1
      active: true

  # (s)niper tower
  - key: s
    down: !switch_updated
      name: right_popper
      active: true
