drivers:
  left_loop_crime_scene_white:
    address: matrix/1/1
    kind: lamp
    name: Left Loop Crime Scene White
    sort_name: Crime Scene, Left Loop White
    manual_name: Perp 1 (White)
    layout:
      - { shape: rect, x: 166, y: 360, w: 19, h: 8, color_name: white }

  left_loop_crime_scene_red:
    address: matrix/1/2
    kind: lamp
    name: Left Loop Crime Scene Red
    sort_name: Crime Scene, Left Loop Red
    manual_name: Perp 1 (Red)
    layout:
      - { shape: rect, x: 166, y: 368, w: 19, h: 8, color_name: red }

  left_loop_crime_scene_yellow:
    address: matrix/1/3
    kind: lamp
    name: Left Loop Crime Scene Yellow
    sort_name: Crime Scene, Left Loop Yellow
    manual_name: Perp 1 (Yellow)
    layout:
      - { shape: rect, x: 166, y: 376, w: 19, h: 8, color_name: yellow }

  left_loop_crime_scene_green:
    address: matrix/1/4
    kind: lamp
    name: Left Loop Crime Scene Green
    sort_name: Crime Scene, Left Loop Green
    manual_name: Perp 1 (Green)
    layout:
      - { shape: rect, x: 166, y: 384, w: 19, h: 8, color_name: green }

  inner_loop_crime_scene_white:
    address: matrix/1/5
    kind: lamp
    name: Inner Loop Crime Scene White
    sort_name: Crime Scene, Inner Loop White
    manual_name: Perp 2 (White)
    layout:
      - { shape: rect, x: 303, y: 168, w: 20, h: 8, color_name: white }

  inner_loop_crime_scene_red:
    address: matrix/1/6
    kind: lamp
    name: Inner Loop Crime Scene Red
    sort_name: Crime Scene, Inner Loop Red
    manual_name: Perp 2 (Red)
    layout:
      - { shape: rect, x: 303, y: 176, w: 20, h: 8, color_name: red }

  inner_loop_crime_scene_yellow:
    address: matrix/1/7
    kind: lamp
    name: Inner Loop Crime Scene Yellow
    sort_name: Crime Scene, Inner Loop Yellow
    manual_name: Perp 2 (Yellow)
    layout:
      - { shape: rect, x: 303, y: 184, w: 20, h: 8, color_name: yellow }

  inner_loop_crime_scene_green:
    address: matrix/1/8
    kind: lamp
    name: Inner Loop Crime Scene Green
    sort_name: Crime Scene, Inner Loop Green
    manual_name: Perp 2 (Green)
    layout:
      - { shape: rect, x: 303, y: 192, w: 20, h: 8, color_name: green }

  right_loop_crime_scene_white:
    address: matrix/2/1
    kind: lamp
    name: Right Loop Crime Scene White
    sort_name: Crime Scene, Right Loop White
    manual_name: Perp 4 (White)
    layout:
      - { shape: rect, x: 394, y: 252, w: 34, h: 8, color_name: white }

  right_loop_crime_scene_red:
    address: matrix/2/2
    kind: lamp
    name: Right Loop Crime Scene Red
    sort_name: Crime Scene, Right Loop Red
    manual_name: Perp 4 (Red)
    layout:
      - { shape: rect, x: 394, y: 260, w: 34, h: 8, color_name: red }

  right_loop_crime_scene_yellow:
    address: matrix/2/3
    kind: lamp
    name: Right Loop Crime Scene Yellow
    sort_name: Crime Scene, Right Loop Yellow
    manual_name: Perp 4 (Yellow)
    layout:
      - { shape: rect, x: 394, y: 268, w: 34, h: 8, color_name: yellow }

  right_loop_crime_scene_green:
    address: matrix/2/4
    kind: lamp
    name: Right Loop Crime Scene Green
    sort_name: Crime Scene, Right Loop Green
    manual_name: Perp 4 (Green)
    layout:
      - { shape: rect, x: 394, y: 276, w: 34, h: 8, color_name: green }

  right_ramp_crime_scene_white:
    address: matrix/2/5
    kind: lamp
    name: Right Ramp Crime Scene White
    sort_name: Crime Scene, Right Ramp White
    manual_name: Perp 5 (White)
    layout:
      - { shape: rect, x: 388, y: 427, w: 18, h: 8, color_name: white }

  right_ramp_crime_scene_red:
    address: matrix/2/6
    kind: lamp
    name: Right Ramp Crime Scene Red
    sort_name: Crime Scene, Right Ramp Red
    manual_name: Perp 5 (Red)
    layout:
      - { shape: rect, x: 388, y: 435, w: 18, h: 8, color_name: red }

  right_ramp_crime_scene_yellow:
    address: matrix/2/7
    kind: lamp
    name: Right Ramp Crime Scene Yellow
    sort_name: Crime Scene, Right Ramp Yellow
    manual_name: Perp 5 (Yellow)
    layout:
      - { shape: rect, x: 388, y: 443, w: 18, h: 8, color_name: yellow }

  right_ramp_crime_scene_green:
    address: matrix/2/8
    kind: lamp
    name: Right Ramp Crime Scene Green
    sort_name: Crime Scene, Right Ramp Green
    manual_name: Perp 5 (Green)
    layout:
      - { shape: rect, x: 388, y: 451, w: 18, h: 8, color_name: green }

  right_popper_crime_scene_white:
    address: matrix/3/1
    kind: lamp
    name: Right Popper Crime Scene White
    sort_name: Crime Scene, Right Popper White
    manual_name: Perp 3 (White)
    layout:
      - { shape: rect, x: 374, y: 159, w: 17, h: 8, color_name: white }

  right_popper_crime_scene_red:
    address: matrix/3/2
    kind: lamp
    name: Right Popper Crime Scene Red
    sort_name: Crime Scene, Right Popper Red
    manual_name: Perp 3 (Red)
    layout:
      - { shape: rect, x: 374, y: 167, w: 17, h: 8, color_name: red }

  right_popper_crime_scene_yellow:
    address: matrix/3/3
    kind: lamp
    name: Right Popper Crime Scene Yellow
    sort_name: Crime Scene, Right Popper Yellow
    manual_name: Perp 3 (Yellow)
    layout:
      - { shape: rect, x: 374, y: 175, w: 17, h: 8, color_name: yellow }

  right_popper_crime_scene_green:
    address: matrix/3/4
    kind: lamp
    name: Right Popper Crime Scene Green
    sort_name: Crime Scene, Right Popper Green
    manual_name: Perp 3 (Green)
    layout:
      - { shape: rect, x: 374, y: 183, w: 17, h: 8, color_name: green }

  lock_1:
    address: matrix/3/5
    kind: lamp
    name: Lock 1
    layout:
      - { shape: circle, x: 222, y: 382, w: 16, h: 16, color_name: green }

  lock_2:
    address: matrix/3/6
    kind: lamp
    name: Lock 2
    layout:
      - { shape: circle, x: 216, y: 362, w: 16, h: 16, color_name: green }

  lock_3:
    address: matrix/3/7
    kind: lamp
    name: Lock 3
    layout:
      - { shape: circle, x: 210, y: 346, w: 16, h: 16, color_name: green }

  super_game_button:
    address: matrix/3/8
    kind: lamp
    name: Super Game Button
    layout:
      - { shape: circle, x: 31, y: 811, w: 20, h: 20, color_name: green }

  class_x_felony:
    address: matrix/4/1
    kind: lamp
    name: Class X Felony
    manual_name: Crime Level 4 (White)
    layout:
      - { shape: rect, x: 350, y: 599, w: 20, h: 42, color_name: white }

  felony:
    address: matrix/4/2
    kind: lamp
    name: Felony
    manual_name: Crime Level 3 (Red)
    layout:
      - { shape: rect, x: 320 , y: 599, w: 20, h: 42, color_name: red }

  misdemeanor:
    address: matrix/4/3
    kind: lamp
    name: Misdemeanor
    manual_name: Crime Level 2 (Yellow)
    layout:
      - { shape: rect, x: 292, y: 599, w: 20, h: 42, color_name: yellow }

  warning:
    address: matrix/4/4
    kind: lamp
    name: Warning
    manual_name: Crime Level 1 (Green)
    layout:
      - { shape: rect, x: 263, y: 600, w: 20, h: 42, color_name: green }

  meltdown:
    address: matrix/4/5
    kind: lamp
    name: Meltdown
    layout:
      - { shape: rect, x: 342, y: 575, w: 26, h: 13, color_name: yellow }

  bad_impersonator:
    address: matrix/4/6
    kind: lamp
    name: Bad Impersonator
    manual_name: Impersonator
    layout:
      - { shape: rect, x: 304, y: 575, w: 26, h: 13, color_name: yellow }

  battle_tank:
    address: matrix/4/7
    kind: lamp
    name: Battle Tank
    layout:
      - { shape: rect, x: 265, y: 575, w: 26, h: 13, color_name: yellow }

  award_meltdown:
    address: matrix/4/8
    kind: lamp
    name: Award Meltdown
    layout:
      - { shape: rect, x: 426, y: 466, w: 15, h: 37, color_name: green }

  stakeout:
    address: matrix/5/1
    kind: lamp
    name: Stakeout
    layout:
      - { shape: rect, x: 411, y: 542, w: 26, h: 13, color_name: yellow }

  safe_cracker:
    address: matrix/5/2
    kind: lamp
    name: Safe Cracker
    layout:
      - { shape: rect, x: 352, y: 545, w: 26, h: 12, color_name: yellow }

  pursuit:
    address: matrix/5/3
    kind: lamp
    name: Pursuit
    layout:
      - { shape: rect, x: 192, y: 546, w: 29, h: 12, color_name: yellow }

  ultimate_challenge:
    address: matrix/5/4
    kind: lamp
    name: Ultimate Challenge
    layout:
      - { shape: rect, x: 297, y: 527, w: 40, h: 21, color_name: orange }

  manhunt:
    address: matrix/5/5
    kind: lamp
    name: Manhunt
    layout:
      - { shape: rect, x: 378, y: 560, w: 26, h: 12, color_name: yellow }

  blackout:
    address: matrix/5/6
    kind: lamp
    name: Blackout
    layout:
      - { shape: rect, x: 226, y: 564, w: 26, h: 12, color_name: yellow }

  sniper:
    address: matrix/5/7
    kind: lamp
    name: Sniper
    layout:
      - { shape: rect, x: 253, y: 547, w: 26, h: 12, color_name: yellow }

  subway_combo:
    address: matrix/5/8
    kind: lamp
    name: Subway Combo
    manual_name: Pick a Prize

  extra_ball:
    address: matrix/6/1
    kind: lamp
    name: Extra Ball
    manual_name: Right Extra Ball
    layout:
      - { shape: circle, x: 179, y: 340, w: 10, h: 10, color_name: orange }
      - { shape: circle, x: 407, y: 232, w: 10, h: 10, color_name: orange }

  right_mode_start:
    address: matrix/6/2
    kind: lamp
    name: Right Mode Start
    sort_name: Mode Start, Right
    manual_name: Right Start Feature
    layout:
      - { shape: circle, x: 366, y: 222, w: 30, h: 30, color_name: yellow }

  center_tank:
    address: matrix/6/3
    kind: lamp
    name: Center Tank
    sort_name: Tank, Center
    layout:
      - { shape: rect, x: 337, y: 209, w: 20, h: 29, color_name: green }

  award_sniper:
    address: matrix/6/4
    kind: lamp
    name: Award Sniper
    layout:
      - { shape: circle, x: 369, y: 196, w: 25, h: 25, color_name: white }

  air_raid:
    address: matrix/6/5
    kind: lamp
    name: Air Raid
    layout:
      - { shape: circle, x: 394, y: 217, w: 14, h: 14, color_name: red }

  left_mode_start:
    address: matrix/6/6
    kind: lamp
    name: Left Mode Start
    sort_name: Mode Start, Left
    manual_name: Left Center Feature
    layout:
      - { shape: circle, x: 225 ,y: 403, w: 30, h: 30, color_name: yellow }

  left_tank:
    address: matrix/6/7
    kind: lamp
    name: Left Tank
    sort_name: Tank, Left
    layout:
      - { shape: rect, x: 183, y: 408, w: 20, h: 32, color_name: green }

  mystery:
    address: matrix/6/8
    kind: lamp
    name: Mystery
    layout:
      - { shape: rect, x: 169, y: 471, w: 17, h: 19, color_name: blue }

  drop_target_j:
    address: matrix/7/1
    kind: lamp
    name: Drop Target J
    layout:
      - { shape: rect, x: 257, y: 320, w: 13, h: 13, color_name: yellow }

  drop_target_u:
    address: matrix/7/2
    kind: lamp
    name: Drop Target u
    layout:
      - { shape: rect, x: 276, y: 310, w: 13, h: 13, color_name: yellow }

  drop_target_d:
    address: matrix/7/3
    kind: lamp
    name: Drop Target D
    layout:
      - { shape: rect, x: 295, y: 301, w: 13, h: 13, color_name: yellow }

  drop_target_g:
    address: matrix/7/4
    kind: lamp
    name: Drop Target G
    layout:
      - { shape: rect, x: 312, y: 289, w: 13, h: 13, color_name: yellow }

  drop_target_e:
    address: matrix/7/5
    kind: lamp
    name: Drop Target E
    layout:
      - { shape: rect, x: 331, y: 278, w: 13, h: 13, color_name: yellow }

  award_safe_cracker:
    address: matrix/7/6
    kind: lamp
    name: Award Safe Cracker
    layout:
      - { shape: rect, x: 334, y: 312, w: 31, h: 13, color_name: orange }

  multiball_jackpot:
    address: matrix/7/7
    kind: lamp
    name: Multiball Jackpot
    layout:
      - { shape: rect, x: 310, y: 323, w: 17, h: 28, color_name: red }

  award_bad_impersonator:
    address: matrix/7/8
    kind: lamp
    name: Award Bad Impersonator
    layout:
      - { shape: rect, x: 289, y: 333, w: 13, h: 35, color_name: orange }

  award_stakeout:
    address: matrix/8/1
    kind: lamp
    name: Award Stakeout

  blackout_jackpot:
    address: matrix/8/2
    kind: lamp
    name: Blackout Jackpot
    layout:
      - { shape: rect, x: 321, y: 134, w: 19, h: 22, color_name: white }

  drain_shield:
    address: matrix/8/3
    kind: lamp
    name: Drain Shield
    layout:
      - { shape: rect, x: 284, y: 703, w: 63, h: 16, color_name: yellow }

  judge_again:
    address: matrix/8/4
    kind: lamp
    name: Judge Again
    layout:
      - { shape: circle, x: 304, y: 741, w: 28, h: 28, color_name: orange }

  advance_crime_level:
    address: matrix/8/5
    kind: lamp
    name: Advance Crime Level
    layout:
      - { shape: rect, x: 357, y: 354, w: 13, h: 28, color_name: white }

  right_tank:
    address: matrix/8/6
    kind: lamp
    name: Right Tank
    sort_name: Tank, Right
    layout:
      - { shape: rect, x: 316, y: 359, w: 31, h: 14, color_name: green }

  extra_ball_button:
    address: matrix/8/7
    kind: lamp
    name: Extra Ball Button
    manual_name: Buy-In
    layout:
      - { shape: circle, x: 593, y: 785, w: 21, h: 21, color_name: yellow }

  start_button:
    address: matrix/8/8
    kind: lamp
    name: Start Button
    layout:
      - { shape: circle, x: 29, y: 775, w: 24, h: 24, color_name: yellow }

  gi_1:
    address: gi/1
    kind: gi
    name: General Illumination 1
    layout:
      - { shape: rect, x: 150, y: 5, w: 15, h: 15, color_name: white }

  gi_2:
    address: gi/2
    kind: gi
    name: General Illumination 2
    layout:
      - { shape: rect, x: 170, y: 5, w: 15, h: 15, color_name: white }

  gi_3:
    address: gi/3
    kind: gi
    name: General Illumination 3
    layout:
      - { shape: rect, x: 190, y: 5, w: 15, h: 15, color_name: white }

  gi_4:
    address: gi/4
    kind: gi
    name: General Illumination 4
    layout:
      - { shape: rect, x: 210, y: 5, w: 15, h: 15, color_name: white }

  gi_5:
    address: gi/5
    kind: gi
    name: General Illumination 5
    layout:
      - { shape: rect, x: 230, y: 5, w: 15, h: 15, color_name: white }
