music:
  - name: bad_impersonator
    path: jd-pinsound/music/000005-bad_impersonator/bad_impe__LEGACY_AUD.wav

  - name: game_over
    path: jd-pinsound/music/000010-end_of_game_match/end_of_g__LEGACY_AUD-fixed.wav

  - name: game_over_matched
    path: jd-pinsound/sfx/000161-end_of_game/end_of_g__LEGACY_AUD.wav

  - name: main_theme
    path: jd-pinsound/music/000002-main_theme/main_the__LEGACY_AUD-fixed.wav

  - name: mode_theme_1
    path: jd-pinsound/music/000004-air_raid/air_raid__LEGACY_AUD.wav

  - name: mode_theme_2
    path: jd-pinsound/music/000003-waiting_sound/waiting___LEGACY_AUD.wav

  - name: multiball_intro
    path: jd-pinsound/music/000009-multi_ball/multi_ba__LEGACY_AUD-intro.wav

  - name: multiball
    path: jd-pinsound/music/000009-multi_ball/multi_ba__LEGACY_AUD-loop.wav

  - name: super_game
    path: jd-pinsound/music/000006-weappon_sound/weappon___LEGACY_AUD-loop1.wav

  - name: super_game_2
    path: jd-pinsound/music/000006-weappon_sound/weappon___LEGACY_AUD-loop2.wav
