scripts:
    multiball:          { module: multiball }
    multiball_audio:    { module: multiball }
    sniper:             { module: sniper, group: mode }
    sniper_audio:       { module: sniper, group: mode }
    sniper_fall:        { module: sniper, group: mode, replace: true }
    sniper_fall_audio:  { module: sniper, group: mode }
    sniper_success:     { module: sniper, group: mode, replace: true }


