sounds:
  - name: announce
    path: jd-pinsound/sfx/000157-wrong/wrong__L__LEGACY_AUD.wav

  - name: bad_impersonator_gunfire
    path: jd-pinsound/sfx/000045-sniper/sniper_2___LEGACY_AUD.wav

  - name: bad_impersonator_throw
    path: jd-pinsound/sfx/000052-bad_inpersonator/bad_inpe__LEGACY_AUD.wav

  - name: ball_lock
    path: jd-pinsound/sfx/000159-option_1/option_1__LEGACY_AUD.wav

  - name: ball_lost
    path: jd-pinsound/sfx/000112-ball_lost/ball_los__LEGACY_AUD.wav

  - name: blackout_jackpot
    path: jd-pinsound/jingle/000154-blackout_jackpot/000154-blackout_jackpot_AUD.wav

  - name: bonus
    path: jd-pinsound/sfx/000063-piano_1/piano_1___LEGACY_AUD.wav

  - name: ding
    path: jd-pinsound/sfx/000101-dring/dring__L__LEGACY_AUD.wav

  - name: drop_target_hit_1
    path: jd-pinsound/sfx/000096-laser_3/laser_3___LEGACY_AUD.wav

  - name: drop_target_hit_2
    path: jd-pinsound/sfx/000097-laser_4/laser_4___LEGACY_AUD.wav

  - name: drop_target_hit_3
    path: jd-pinsound/sfx/000098-laser_4/laser_4__2_LEGACY_AUD.wav

  - name: drop_target_hit_4
    path: jd-pinsound/sfx/000099-laser_5/laser_5___LEGACY_AUD.wav

  - name: drop_target_hit_5
    path: jd-pinsound/sfx/000100-flash_2/flash_2___LEGACY_AUD.wav

  - name: gun_load_sniper
    path: jd-pinsound/sfx/000132-gun_loading_1/gun_load__LEGACY.wav

  - name: gunfire
    path: jd-pinsound/sfx/000133-gun_fire/gun_fire__LEGACY_AUD.wav

  - name: left_popper_laser
    path: jd-pinsound/sfx/000068-laser_2/laser_2___LEGACY_AUD.wav

  - name: left_post
    path: jd-pinsound/sfx/000151-wrong_signal/wrong_si__LEGACY_AUD.wav

  - name: left_shooter_lane_fire
    path: jd-pinsound/sfx/000041-fire/fire__LE__LEGACY_AUD.wav

  - name: manhunt_auto_fire
    path: jd-pinsound/sfx/000040-manhunt_mode/manhunt___LEGACY_AUD.wav

  - name: manhunt_single_fire
    path: jd-pinsound/sfx/000133-gun_fire/gun_fire__LEGACY_AUD.wav

  - name: meltdown_cracking
    path: jd-pinsound/sfx/000135-wood_broken/wood_bro__LEGACY.wav

  - name: meltdown_explosion
    path: jd-pinsound/sfx/000128-very_big_explosion/very_big__LEGACY_AUD.wav

  - name: meltdown_klaxon
    path: jd-pinsound/sfx/000134-alarm/alarm__L__LEGACY_AUD.wav

  - name: motorcycle_ramp
    path: jd-pinsound/sfx/000102-motorcycle_noise_2/motorcyc__LEGACY_AUD.wav

  - name: motorcycle_start
    path: jd-pinsound/sfx/000103-motorcylce_start/motorcyl__LEGACY_AUD.wav

  - name: motor_rev
    path: jd-pinsound/sfx/000074-motor_noise/motor_no__LEGACY_AUD.wav

  - name: multiball_jackpot
    path: jd-pinsound/jingle/000155-special_option/special___LEGACY_AUD.wav

  - name: mystery
    path: jd-pinsound/sfx/000124-criquet_sound/criquet___LEGACY_AUD.wav

  - name: point
    path: jd-pinsound/sfx/000106-point/point__L__LEGACY_AUD.wav

  - name: police_siren
    path: jd-pinsound/sfx/000141-police_horn/police_h__LEGACY_AUD.wav

  - name: pursuit_engine
    path: jd-pinsound/sfx/000042-pursuit_mode/pursuit___LEGACY_AUD.wav

  - name: pursuit_explosion
    path: jd-pinsound/sfx/000066-little_explosion/little_e__LEGACY_AUD.wav

  - name: pursuit_missile
    path: jd-pinsound/sfx/000100-flash_2/flash_2___LEGACY_AUD.wav

  - name: return_lane
    path: jd-pinsound/sfx/000122-explosion_3/explosio__LEGACY.wav

  - name: right_post
    path: jd-pinsound/sfx/000152-wrong_signal_1/wrong_si__LEGACY_AUD.wav

  - name: right_ramp
    path: jd-pinsound/sfx/000095-special_gun_fire/special___LEGACY_AUD.wav

  - name: shock
    path: jd-pinsound/sfx/000049-bad_inpersonator/bad_inpe__LEGACY_AUD.wav

  - name: sling
    path: jd-pinsound/sfx/000107-check_point/check_po__LEGACY_AUD.wav

  - name: safecracker_explosion
    path: jd-pinsound/sfx/000093-big_explosion/big_expl__LEGACY_AUD.wav

  - name: safecracker_gunfire_1
    path: jd-pinsound/sfx/000040-manhunt_mode/manhunt___LEGACY_AUD.wav

  - name: safecracker_gunfire_2
    path: jd-pinsound/sfx/000085-laser_fire/laser_fi__LEGACY_AUD.wav

  - name: safecracker_laser_fire
    path: jd-pinsound/sfx/000095-special_gun_fire/special___LEGACY_AUD.wav

  - name: safecracker_tank_fire
    path: jd-pinsound/sfx/000041-fire/fire__LE__LEGACY_AUD.wav

  - name: sniper_splat
    path: jd-pinsound/sfx/000076-hurt_3/hurt_3____LEGACY_AUD.wav

  - name: sniper_tower
    path: jd-pinsound/sfx/000069-guitar_2/guitar_2__LEGACY_AUD.wav

  - name: snore
    path: jd-pinsound/sfx/000203-criquet_1/criquet___LEGACY_AUD.wav

  - name: success
    path: jd-pinsound/jingle/000153-accepted_sound/accepted__LEGACY_AUD.wav

  - name: tank_destroyed
    path: jd-pinsound/sfx/000066-little_explosion/little_e__LEGACY_AUD.wav

  - name: tank_fire
    path: jd-pinsound/sfx/000066-little_explosion/little_e__LEGACY_AUD.wav

  - name: tire_squeal_1
    path: jd-pinsound/sfx/000072-rustling_tire/rustling__LEGACY_AUD.wav

  - name: tire_squeal_2
    path: jd-pinsound/sfx/000073-rustling_tire_1/rustling_2_LEGACY_AUD.wav

  - name: top_left_ramp
    path: jd-pinsound/sfx/000083-extra_sound/extra_so__LEGACY_AUD.wav

  - name: walking
    path: jd-pinsound/sfx/000146-walking_sound/walking___LEGACY_AUD.wav
