module_name: jd

scripts:
  init:   { module: init }
  gi_on:  { module: init }
  main:   { module: main }

std:
  - dmd
  - game
  - player_4
  - service

video:
  dmd:
    width: 128
    height: 32
    layers: 2

sdl:
  audio:
    output: mono
    channels: 4
    with_mp3: true
    with_ogg: true
  dmd:
    video: dmd
  image:
    with_jpeg: true
    with_png: true
  monitor:
    playfield: monitor/judge-dredd-648x864.jpg

vars:
  free_play:  { kind: !bool true }




