vocals:
  mega_city_one_is_blacked_out_be_on_the_lookout_for_looters:
    path: jd-pinsound/voice/3609427385-megocity_one_is_blacked_out_be_on_the_alert_for_looters/megocity__LEGACY.wav

  send_backup_units:
    path: jd-pinsound/voice/000260-send_backup_units/send_bac__LEGACY_AUD.wav

  blackout_jackpot:
    path: jd-pinsound/jingle/000154-blackout_jackpot/000154-blackout_jackpot_AUD.wav


