vocals:
  fool_death:
    path: jd-pinsound/voice/000264-fool/fool__LE__LEGACY_AUD.wav

  i_thought_i_stopped_you:
    path: jd-pinsound/voice/000341-i_thought_i_stopped_you/i_though__LEGACY_AUD.wav

  you_cannot_contain_me:
    path: jd-pinsound/voice/000277-you_cannot_contain_me/you_cann__LEGACY_AUD.wav

  you_cannot_kill_what_does_not_live:
    path: jd-pinsound/voice/000265-you_cannot_kill_what_does_not_live/you_cann__LEGACY_AUD.wav

