run_groups:
  sniper: { parent: mode }


scripts:
  sniper:                 { module: sniper, group: mode, replace: true }
  sniper_audio:           { module: sniper, group: sniper }
  sniper_draw:            { module: sniper, group: sniper }
  sniper_failure:         { module: sniper, group: mode, replace: true }
  sniper_fall:            { module: sniper, group: mode, replace: true }
  sniper_fall_audio:      { module: sniper, group: sniper }
  sniper_fall_draw:       { module: sniper, group: sniper }
  sniper_fall_intro_draw: { module: sniper, group: sniper }
  sniper_fall_timer_draw: { module: sniper, group: sniper }
  sniper_intro_draw:      { module: sniper, group: sniper }
  sniper_score_draw:      { module: sniper, group: sniper }
  sniper_success:         { module: sniper, group: mode, replace: true }

  test_sniper_failure:      { module: sniper, test: true }
  test_sniper_fall_failure: { module: sniper, test: true }
  test_sniper_success:      { module: sniper, test: true }


timers:
  sniper_score:
    var: sniper_score
    start: 20000000
    end: 3000000
    step: -78330
    tick: 0.16 # sec
    expire_delay: 2 # sec
    group: sniper

  sniper_fall:
    var: sniper_fall_timer
    start: 15
    group: sniper


vars:
  sniper_score:       { kind: !int 0 }
  sniper_fall_timer:  { kind: !int 0 }

namespaces:
  player:
    sniper_bonus:     { kind: !int 0 }

vocals:
  aaaaah:
    path: jd-pinsound/voice/000282-aaaaaaaaaaaaaaaaaaaah/aaaaaaaa__LEGACY_AUD.wav

  i_can_see_my_house_from_here:
    path: jd-pinsound/voice/000284-i_can_see_my_house_from_here/i_can_se__LEGACY_AUD.wav

  its_a_long_way_down:
    path: jd-pinsound/voice/000283-it_s_a_long_way_down/it_s_a_l__LEGACY_AUD.wav

  shoot_sniper_tower:
    path: jd-pinsound/voice/000356-shoot_sniper_tower/shoot_sn__LEGACY_AUD.wav

  sniper_eliminated:
    path: jd-pinsound/voice/000253-sniper_eliminated/sniper_e__LEGACY_AUD.wav

  sniper_is_shooting_into_the_crowd_from_johnson_tower:
    path: jd-pinsound/voice/000346-sniper_is_shooting_into_crowd_from_johnson_tower/sniper_i__LEGACY.wav


sounds:
  gun_load_sniper:
    path: jd-pinsound/sfx/000132-gun_loading_1/gun_load__LEGACY.wav

  gunfire:
    path: jd-pinsound/sfx/000133-gun_fire/gun_fire__LEGACY_AUD.wav

  sniper_splat:
    path: jd-pinsound/sfx/000076-hurt_3/hurt_3____LEGACY_AUD.wav

  success_sniper:
    path: jd-pinsound/jingle/000153-accepted_sound/accepted__LEGACY_AUD.wav
    duck: 0.5

